- filer/admin/folderadmin.py
- filer/views.py
Files will be sorted according to order_by parameter if exists. If this parameter is not
set, then files are sorted as before (by its str representation, its name or original_filename). 
This parameter can be set to a list of fields separated by commas in order to sort by more than one field.
After pasting a file from the clipboard, the directory listing is called with this parameter
set to -modified_at. Therefore, the pasted element could be more easily selected.
> Add order_by parameter in directory listing (set to -modified_at when paste from clipboard)

- filer/migrations_django/0002_image.py
Skip the new 0002_image django 1.7 migration if table already exists for compatibility with previous migration structure
> Skip new migration if table already exists

- filer/fields/file.py
- filer/static/filer/js/popup_handling.js
- filer/static/filer/js/widget.js
- filer/templates/admin/filer/widgets/admin_file.html
How to reproduce :
Use a FilerField in a ManyToMany, and use admin's inline to manage it in the admin form.
When "add new row" is clicked, the "clear" image is displayed and not functionnal.
This is because the old javascript is for the current ID, so new lines, with != IDs, couldn't work. This bug fix use classes and the jQuery(document).on function to watch event on newly created lines.
> generic JS usable when a row is duplicated when file is a part of a ManyToMany

- filer/models/abstract.py
when IOError('encoder jpeg not available',)
-->  logger.error('Error while generating thumbnail: %s',e)
line 139 (now 141)
> global name 'logger' is not defined

- filer/models/filemodels.py
I ran across this issue when using this code with Django 1.8. I copied this solution: https://github.com/lukaszb/django-guardian/pull/287
Sorry, but I did not run tests yet. I was having an issue getting them to work. 
Please advise any changes.
> Updated get_admin_url_path to work with django 1.8 deprecation 

- filer/templates/admin/filer/folder/directory_table.html
There is an extra quote character which will make the HTML invalid. Also brakes syntax highlighting of the file (because of invalid syntax)
> Fix bad HTML - Remove extra quote character

- filer/static/filer/js/jquery.cookie.js
- filer/templates/admin/filer/tools/upload_button_js.html
This makes filer work in admin modules that does not define $ or jQuery in the global scope.
(All the other scripts already use django.jQuery)
> Added scope-wrapper function to use django.jQuery

- filer/migrations/0002_auto_20150606_2003.py
- setup.py
django-polymorphic==0.7 changed the reverse relation for the polymorphic
content-type. Django 1.7 migrations detects this as a change (although
nothing changes at database level).
South does not detect this as a change and does not need a new
migration.
This commit introduced the necessary change: https://github.com/chrisglass/django_polymorphic/compare/v0.6.1...v0.7#diff-22a782d7dcedbbbe6a4efdadd17dadc9R59
> add migration for recent django-polymorphic

- filer/models/abstract.py
- filer/utils/pil_exif.py
the storages backend doesn't implement path() as it should be, but filer requires that.
> Fix unsupported backend error when using s3 in django-storages

- AUTHORS
- filer/templates/admin/filer/tools/clipboard/clipboard.html
- filer/templates/admin/filer/tools/clipboard/clipboard_item_rows.html
BTW: There is a feature branch ready to merge django-smart-load-tag into filer on my side. 
Fix #560
> Remove unused 'thumbnail' template tags to avoid conflicts - fixes #560

- .travis_setup
- filer/admin/folderadmin.py
- filer/admin/tools.py
- filer/tests/admin.py
Views in admin site use a context which includes properties like
"site_head" and "site_url". This properties are used by base admin
templates.
Previously, FolderAdmin was creating a new context in his views
functions, not including default properties.
Now, FolderAdmin starts from the base context of every admin view.
This uses function each_context which is available in django>=1.7, so
the new behaviour is only from that version upwards.
> FolderAdmin uses base admin context in views

- filer/static/filer/css/admin_style.css
- filer/templates/admin/filer/folder/directory_table.html
- filer/templates/admin/filer/image/change_form.html
Thumbnails in the directory table and the preview image now has a light checkerboard pattern background (that turns dark on mouseover) to make both light and dark transparent images easier to see.
Uses two small gif's embedded in the css using data urls so that it doesn't add additional http requests.
> Added checkerboard tiles as background to thumbnails. Fix for issue #562

- filer/admin/tools.py
- filer/utils/compatibility.py
* If you installed Django==1.8.0, django.get_version() > '1.8' was
False
* If you would to install Django==1.10, django.get_version() > '1.8'
would be False
* Strings are not meant to be compared like numbers
> Fix django comparison

- HISTORY
The changelog (HISTORY) had two entries for version 1.0.0. I kept the more recent one that was in the correct place chronologically.
The only line that differed between the two were:
- Retained: ```* Remove `FILER_STATICMEDIA_PREFIX` and use `staticfiles` for static files.```
- Discarded: `* Abandons FILER_STATICMEDIA_PREFIX in favor of Django's MEDIA_ROOT`
> Remove duplicated history entry for 1.0.0

- filer/templates/admin/filer/widgets/admin_file.html
- filer/templates/admin/filer/widgets/admin_folder.html
- filer/templates/admin/filer/widgets/lookup.html
- filer/templatetags/filer_admin_tags.py
Basically django 1.8 no longer needs the onclick() action so if rendered then it causes the list endpoint to be called twice and create a race condition in multi-thread environments.
> adds hotfix for django 1.8

- setup.py
- tox.ini
Pin django-polymorphic version to be below 0.8.
Also pins django-mptt in tox.
Note: Travis build is currently broken only because of django-mptt version being dependent on Django version. We'd better merge this quickly and do a version bump/release to fix issue for all the possible users.
The next steps: 
* fix travis setup based on #643 
* really support new django-polymorphic (broken because of imports and queryset methods proxying)
> Pin django-polymorphic

- .travis.yml
- tox.ini
Improve tox/travis setup for front-end tests to make running front-end test suite locally easier.
* Move gulp commands from travis to tox, simplify travis setup
* Reorder `apt-get` and `npm` commands
This is a PR against the `develop` branch, as we have all front-end related improvements there.
> Improve tox/travis setup for front-end tests

- filer/admin/folderadmin.py
search_form.html template makes use of these variables, but they were
not set in the context.
> folder admin: add missing search results querysets to context

- filer/admin/clipboardadmin.py
- filer/settings.py
There is some code in the wild that depends on this being strings. Namely, django-cms plugin Filer.
> Convert FILER_ADMIN_ICON_SIZES elements to strings

- filer/admin/clipboardadmin.py
File upload view changes required for better drag-n-drop support.
* Include original image URL on AJAX file upload
* Move ajax_upload view out of ClipboardAdmin to allow to import it
(~~Please, do not merge yet.~~ Would go into the release after the ~~next~~ current one, which would probably be 1.1.1.)
> Image upload handler improvements

- filer/management/commands/import_files.py
This will make `import_files` to work again on Python 3
> When import files open them in binary mode

- filer/fields/file.py
- filer/fields/folder.py
fixes #630 Running management commands fails when using ManifestStaticFilesStorage
> remove unnecessary call to static for widget media

- filer/templates/admin/filer/widgets/admin_file.html
The path `filer/icon/nofile_48x48.png` doesn't exist, use the correct one.
This bug surfaced when using ManifestStaticFilesStorage in combination with djangocms-page-meta. Accessing a non existing file raised an exception, which broke the forms render method, therefore not rendering the form at all.
> Fix wrong icon path in admin file widget

- filer/admin/folderadmin.py
- filer/tests/admin.py
- Fix 'rename_files' action for 'unfiled' files.
- Add a few simple admin view tests.
> Fix renaming files without folders

- filer/apps.py
|BEFORE|AFTER|
|---|---|
|![2016-04-14_1620](https://cloud.githubusercontent.com/assets/2270884/14566602/7c0b0f94-0330-11e6-804a-4da54e5fe291.png)|![screen shot 2016-04-15 at 17 35 02](https://cloud.githubusercontent.com/assets/2270884/14566603/80620f16-0330-11e6-877c-957eaa6d5c18.png)|
> rename django filer to Filer in breadcrumbs

- filer/south_migrations/0016_auto__chg_field_image_subject_location.py
If there is existing rows in the database with subject_location=Null the
migration failed (on postgres).
This sets all Null fields to an empty string to prevent the error.
For projects who have already run this migration:
- if they were using a db backend where this does not matter: it does not matter
- if they were running a db backend where it does matter (postgres) and they had no null entries: all is fine
-  if they were running a db backend where it does matter (postgres) and they had null entries: the migration failed and thus has not run yet
For all the above cases it is fine that we just altered an existing migration instead of creating a new one.
~~Does anyone know if the same error occurs with the new style migrations?~~ I can confirm that the new style migrations work out of …
> fix: south migration for subject_location fails

- filer/migrations/0005_auto_20160429_1025.py
This migration was left out of the latest version. It is being ignored by Django 1.8/1.9 and cms-helper (which is probably how it happened), but it brings the DB to the correct state (change of a default value to subject_location) and tests work in both cases.
> Add missing migration

- README.rst
- docs/installation.rst
- docs/running_tests.rst
As per [their blog post of the 27th April](https://blog.readthedocs.com/securing-subdomains/) ‘Securing subdomains’:
> Starting today, Read the Docs will start hosting projects from subdomains on the domain readthedocs.io, instead of on readthedocs.org. This change addresses some security concerns around site cookies while hosting user generated data on the same domain as our dashboard.
Test Plan: Manually visited all the links I’ve modified.
> Convert readthedocs links for their .org -> .io migration for hosted projects

- filer/static/filer/js/addons/upload-button.js
On reload the query parameters were added after the hash. This PR fixes this bug by cutting the hash and putting it back after computing the new uri.
> Take hash into account when reloading

- filer/models/foldermodels.py
Djangos default behaviour is to cascade the deletion of a user, which results in the deletion of files and folders.
Also on_delete will become a required argument in Django 2.0.
> Change on_delete behaviour

- filer/admin/fileadmin.py
- filer/admin/folderadmin.py
``FileAdmin.render_change_form`` forces add / change argument values, while it's feasible to use add view to create files without using the clipboard
> Fixed add/change arguments in FileAdmin.render_change_form

- .travis.yml
- filer/models/abstract.py
- filer/models/imagemodels.py
- filer/test_utils/extended_app/models.py
- filer/test_utils/urls.py
- filer/utils/compatibility.py
- setup.py
- test_requirements/django-1.10.txt
- tox.ini
Based on #911.
Also, the various compatibility helpers _litter_ the code base. Are we okay to drop Django < 1.8? Obviously in a separate PR.
> Upgrade django

- filer/admin/folderadmin.py
- filer/templates/admin/filer/folder/directory_table.html
- filer/templatetags/filer_admin_tags.py
- filer/tests/admin.py
Fixes #868.
Instead of checking to see if we should show the permissions link for all items, only do that check for items that we are displaying.
Adds a template tag that tells us whether we have permission to do an action on the item. This could be moved into Python if we rather, but would mean faffing about with the items inside the page that the paginator gives us, which seemed less Django-ish.
> Admin: directory-listing permissions speedup

- filer/admin/fileadmin.py
- filer/templates/admin/filer/file/change_form.html
In Django 1.9 history link is at the same level of the changeview
> Fix history link in Django 1.9+

- filer/admin/folderadmin.py
- filer/fields/multistorage_file.py
- filer/models/abstract.py
- filer/models/filemodels.py
This is a complete rework of part of #500 relating to size, sha1, width and height recalculation. Current implementation is based on how Django's ImageFileField recalculates width, height. Basically, instead of updating these fields in `save()`, they are updated immediately after MultiStorageFileField value is set.
I also improved change detection in descriptor a bit by checking whether field value is actually changed and detecting calls originating from model's `__init__` properly.
> size, sha1 and width, height field recalculation overhaul

- CHANGELOG.txt
- filer/templates/admin/filer/folder/directory_listing.html
> removes arrow in breadcrumbs if no following folder or name

- filer/admin/folderadmin.py
- filer/tests/admin.py
This avoids wrongly unescaping characters that aren't escaped by the browser, like underscores.
> Replaces django's extended unquote function with urlunquote

- filer/templates/admin/filer/folder/choose_copy_destination.html
- filer/templates/admin/filer/folder/choose_move_destination.html
According to [a comment](https://github.com/divio/django-filer/commit/580e65b09809fcc4ffcd33a1756b40d966199146#commitcomment-17782172) left on the commit that introduced the bug, the location of the jquery.js file has changed in Django 1.9 (as stated in the [release notes](https://docs.djangoproject.com/en/1.9/releases/1.9/#miscellaneous)).
This is a severe problem if you use the `ManifestStaticFilesStorage` as it will cause a 500 error on the move and copy pages (`the file admin/js/jquery.js could not be found with django.contrib.staticfiles.storage.ManifestStaticFilesStorage`).
> Fix jQuery loading on file move/copy page with Django 1.9

- CHANGELOG.txt
- filer/templatetags/filer_image_tags.py
Often the image has to be used as a background-image for the container
which size is unknown. Usual way of doing it is setting background image
to the container and using `background-size: cover;`. However if you do
that - focal point position won't be respected. With this template tag
you can now do the following:
```
{% load filer_image_tags %}
<div class="hero"
style="background-image: url({{ image.url }}; background-position: {{ image|get_css_position }};">
I'm a hero unit
</div>
```
And the image would be positioned correctly.
> Feature request: `get_css_position` filter

- filer/templates/admin/filer/widgets/admin_file.html
In Django 1.11 admin the dropzone widget is not displayed properly -- it always shows an empty blue button next to the "Choose file" button.
> Fix widget UI issue with Django 1.11

- .travis.yml
- filer/admin/imageadmin.py
- osx tests: fallback to xcode7.3 to run pip
- flake8: reorder imports on admin/imageadmin.py
Fix by @duartefq 
Part of #1042
> Fix travis tests

- test_requirements/base.txt
pillow 5.1.0 is broken on OS X 10.11 we use on travis
> Fix mac os builds

- filer/models/filemodels.py
Merge #995 
Fix #994 (Canonical URLs computation)
Fixes the computation of Canonical URLs to behave as before commit 878cafe.
> Merge #995

- .travis.yml
- docs/installation.rst
- setup.py
- test_requirements/django-1.10.txt
- test_requirements/django-1.11.txt
- test_requirements/django-1.8.txt
- test_requirements/django-1.9.txt
- test_requirements/django-master.txt
Thing is, that polymorphic 1.3 has nasty bug when swapped models are used (like swapped Image model in filer). See django-polymorphic/django-polymorphic@02330a5ec835b118d67aacf071cc2deef1250829. Unfortunately, the fix is only included in django-polymorphic 2.0 which only supports Django 1.11 and newer. The problem first appeared in Django 1.10, so it is impossible to have polymorphic swapped model with released version of django-polymorphic.
Therefore, for people using swapped image model and Django 1.11, django-polymorphic 2.0 is required.
> allow django_polymorphic==2.0

- CHANGELOG.txt
- filer/admin/fileadmin.py
Remove the hack (as defined by the code comment) so the button is not
visible anymore.
Also, it seems to me that the 'hack' is not needed anymore - if it's still needed, this PR might introduce breaking changes.
> Fix #1035 -- Hide 'Save as new' button

- filer/admin/imageadmin.py
- filer/test_utils/custom_image/models.py
- filer/tests/admin.py
Some tests have been disabled for extended images
They can be safely re-enabled now along with some further fixes for extended images
#1079 must be applied first to allow tests to run here
> Reenable missing tests for custom image models

- filer/static/filer/js/addons/copy-move-files.js
- filer/static/filer/js/addons/dropdown-menu.js
- filer/static/filer/js/addons/dropzone.init.js
- filer/static/filer/js/addons/focal-point.js
- filer/static/filer/js/addons/popup_handling.js
- filer/static/filer/js/addons/table-dropzone.js
- filer/static/filer/js/addons/toggler.js
- filer/static/filer/js/addons/upload-button.js
- filer/static/filer/js/addons/widget.js
- filer/static/filer/js/base.js
The initialisation of jQuery has some delay and may still be attached to window.$. To be safe make sure it is found otherwise drag & drop and selecting an image would fail.
> Widgets do not work under Django 2.x

- filer/fields/file.py
Fixed a typo error merged on #1120 .
AdminFileWidget must receive _renderer_ argument instead of _render_.
> Fixed: renderer instead of render argument in AdminFileWidget render

- CHANGELOG.txt
- filer/fields/file.py
> Fixed #1125 - missing validation message for empty file field in file and image widget

- filer/fields/file.py
Dropzone requires jQuery, so it should be listed in here. Otherwise the output order might be different.
Fixes #1103
> Add jQuery as AdminFileWidget Media dependency

- CHANGELOG.rst
- filer/models/mixins.py
- filer/templates/admin/filer/base_site.html
- filer/templates/admin/filer/change_form.html
- filer/templates/admin/filer/delete_confirmation.html
- filer/templates/admin/filer/file/change_form.html
- filer/templates/admin/filer/folder/change_form.html
- filer/templates/admin/filer/folder/choose_copy_destination.html
- filer/templates/admin/filer/folder/choose_images_resize_options.html
- filer/templates/admin/filer/folder/choose_move_destination.html
- filer/templates/admin/filer/folder/directory_listing.html
- filer/templates/admin/filer/folder/directory_table.html
- filer/templates/admin/filer/image/change_form.html
- filer/templates/admin/filer/tools/detail_info.html
- filer/templates/admin/filer/tools/search_form.html
- filer/templates/admin/filer/widgets/admin_file.html
- filer/templates/admin/filer/widgets/admin_folder.html
In recent versions of Django, the templatetag `staticfiles` has been replaced against `static`. Since Django-2.1 there is a deprecation warning that this templatetag will be removed in Django-3.
Even though this pull request is mandatory, I have little hope that it will be merged soon, considering my experience with the maintainers of django-filer, which even ignore to comment other useful pull requests awaiting to be merged.
> Refactor all occurences of templatetag staticfiles against static

- setup.py
Resolves dependency issue in other projects where Unidecode >= 1.1 is needed.
> Allow latest unidecode version

- CHANGELOG.rst
- filer/templates/admin/filer/tools/detail_info.html
On upload, django-filer renames files so that they are case-insensitive, without spaces and dots. This however is not what a user expects when he wishes to download that file again.
By adding the property [download="..."](https://www.w3schools.com/tags/att_a_download.asp) to the link, we can restore the expected behaviour.
> Use property ‘download’ to reuse original filename

- CHANGELOG.rst
- filer/__init__.py
* Added Django 3.0 support
* Added support for Python 3.8
* Add attribute ``download`` to the download link in order to offer the file
under its original name.
> Bumped version to 1.7.0

- filer/admin/folderadmin.py
There is a small typo in filer/admin/folderadmin.py.
Should read `recursively` rather than `recursivelly`.
> docs: Fix simple typo, recursivelly -> recursively

- filer/fields/file.py
Because filer was requesting jquery.js in non-DEBUG instead of jquery.min.js (like django does), both were being included in the Media output. jquery.js was being included after jquery.min.js and more importantly django's jquery.init.js, so it was polluting the global namespace. This was observed in Django 1.11 and may not be a problem on later versions.
The fix simply uses jquery.min.js in non-debug mode.
> fixes #1188 loading jquery.js after jquery.min.js had been loaded

- CHANGELOG.rst
- setup.py
The name with an underscore works, but just looks off in a `requirements.txt`. Also it will create unnecessary diffs when using tools such as [prequ](https://github.com/suutari/prequ) when an other `setup.py` has specified the name with a dash.
> Use dashed name for django-polymorphic in setup.py

- CHANGELOG.rst
- filer/__init__.py
* Added support for Django 3.1
* Dropped support for Python 2.7 and Python 3.4
* Dropped support for Django < 2.2
* Changed the preferred way to do model registration via model inheritance
and ``mptt.AlreadyRegistered``, which is deprecated since django-mptt 0.4
* Use dashed name for django-polymorphic dependency in setup.py
> Bumped version to 2.0.0

- filer/utils/files.py
This is a quick fix for #1211 (solution 1).
It guesses the MIME-type using the filename suffix, rather than relying on the `Content-Type` sent by the server.
Should be reviewed as soon as possible, because it fixes a blocker bug.
> fix #1211: On upload MIME-type is not set correctly

- filer/utils/files.py
Upper/mixed case file extensions won't be found in  mimetypes.guess_all_extensions(mime_type)
> Fix for uppercase file extensions mimetype error

- filer/models/foldermodels.py
`FolderManager` seems unused and non-working since its introduction in cec6054df3fb96af5d0060f4bdae219f92ff1940. Also it shadows `mptt.TreeManager`.
> Removed never used and non-working FolderManager.

- filer/admin/permissionadmin.py
Filer's permission admin page scales really bad for a larger user base (>280k entries) and a lot of permissions - so here are the patches I use to cope with it.
> Improve PermissionAdmin performance

- filer/static/filer/js/addons/dropzone.init.js
Fx dropzone error callback for admin fields which has not good parameters (`file, response` instead of `file, error, response`)
Dropzone documentation say:  
> An error occured. Receives the errorMessage as second parameter and if the error was due to the XMLHttpRequest the xhr object as third.  
https://www.dropzonejs.com/#event-error
> fix dropzone error callback for admin fields

- filer/models/filemodels.py
In order to prevent `OSError` with 'resource busy' the source file on file move should not be open when deleting it via the storage system.
Closes #1184
> Close file before deletion on file move

- README.rst
Document the fact that Python 3.6 is required as already described in the changelog.
> fix: readme is missing the updated requirement on Python 3.6

- CHANGELOG.rst
- filer/apps.py
This defines a ``default_auto_field`` on the app config so django won't try to create migrations for the app if someone moves their project to big auto field.
* #1293
> fix: Define a ``default_auto_field`` on the app config

- .github/stale.yml
There's issues dating back to 2011. Implementing stale bot on django-cms has had a positive impact so far, so this brings over the same config.
> Added stale bot config

- filer/private/sass/components/_drag-and-drop.scss
Fix file widget on mobile devices.
Before/After:
> fix: file widget styling on mobile devices

- setup.py
Since version 2.8.2 of [easy-thumbnails](https://github.com/SmileyChris/easy-thumbnails) one must explicitly install the extra dependencies for SVG. This is done by `pip install easy-thumbnails[svg]`.
This pull request fixes this installation problem.
https://github.com/SmileyChris/easy-thumbnails/pull/597
> Install django-filer with SVG support

- docs/README.rst
- docs/secure_downloads.rst
- filer/admin/folderadmin.py
- filer/models/foldermodels.py
- filer/templatetags/filer_admin_tags.py
- filer/thumbnail_processors.py
- tests/helpers.py
- tests/test_admin.py
There are small typos in:
- docs/README.rst
- docs/secure_downloads.rst
- filer/admin/folderadmin.py
- filer/models/foldermodels.py
- filer/templatetags/filer_admin_tags.py
- filer/thumbnail_processors.py
- tests/helpers.py
- tests/test_admin.py
Fixes:
- Should read `suitable` rather than `suitiable`.
- Should read `rendered` rather than `redered`.
- Should read `outer` rather than `owter`.
- Should read `permission` rather than `permisison`.
- Should read `library` rather than `libary`.
- Should read `initial` rather than `inital`.
- Should read `ellipse` rather than `elipse`.
- Should read `deletable` rather than `deleteable`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- CHANGELOG.rst
- aldryn_config.py
Remove hardcoded settings from alrdryn_config.py and use the defaults
provided by easy-thumbnails.
Fixes #1310
> Fix thumbnail generation for SVG images when used as a Divio addon

- filer/static/filer/js/addons/popup_handling.js
Django 4.1 adds a [popup index to the admin popup window name](https://github.com/django/django/commit/492ed60f236d770eb9a6d56d85ff2550bb1ecfff) that needs to be stripped when getting back to the element id.
This should be backwards compatible to previous element ids unless they use double underscores (`__`) in them.
> Fix popup window name to element id transform

- .github/workflows/test.yml
- CHANGELOG.rst
- README.rst
- filer/server/backends/default.py
- setup.py
- tests/requirements/django-4.1.txt
This PR adds tests for Django 4.1 and Python 3.11 
* The size argument to `was_modified_since()` has been removed (https://docs.djangoproject.com/en/4.1/releases/4.1/#miscellaneous)
> feat: Add django 4.1 and Python 3.11 support

- .github/workflows/pre-commit.ci.yaml
- .pre-commit-config.yaml
- filer/templatetags/filer_admin_tags.py
easy-thumbnails's `thumbnailer.get_options()` accepts parameter `options` as type `ThumbnailerOptions` but it current is passed as dict. This PR fixes that.
* [easy-thumbnails](https://github.com/SmileyChris/easy-thumbnails)
> use ThumbnailOptions instead of a dict

- filer/utils/files.py
- setup.py
Remove Unidecode dependency to avoid GPL clashes.
* https://github.com/django-cms/django-filer/issues/1266
> Removing Unidecode dependency to avoid GPL clashes

- filer/templates/admin/filer/delete_selected_files_confirmation.html
- filer/templates/admin/filer/folder/choose_copy_destination.html
- filer/templates/admin/filer/folder/choose_images_resize_options.html
- filer/templates/admin/filer/folder/choose_move_destination.html
- filer/templates/admin/filer/folder/choose_rename_format.html
- filer/templates/admin/filer/folder/directory_listing.html
- filer/templates/admin/filer/folder/directory_table_list.html
- filer/templates/admin/filer/folder/directory_thumbnail_list.html
- filer/templates/admin/filer/tools/clipboard/clipboard.html
This fixes issue #1335. 
A similar change has been merged into django cms core (https://github.com/django-cms/django-cms/pull/7188)
* #1335
* #...
> fix: Some id were localized in the templates

- filer/admin/clipboardadmin.py
- filer/admin/folderadmin.py
- filer/models/filemodels.py
- filer/models/foldermodels.py
- tests/test_admin.py
- tests/test_dump.py
- tests/test_permissions.py
- tests/test_tools.py
This PR fixes a **security issue**: A **staff user without any permissions** 
* Can browse the filer folder structure 
* List files in a folder
* Add files
* Move files and folders
Thanks to Akshar Tank for reporting this issue.
This fix enforces the following permissions
* `can_use_directory_listing` 
* `change_folder`
* `add_folder`
* `add_file`(also for drag&drop upload)
* Users need to have the permission `add_file` to upload files
* Users need to have the permission `can_use_directory_listing` to browse the filer folders
* 
* #...
* #...
> fix: respect upload and directory listing permissions

- CHANGELOG.rst
- filer/models/filemodels.py
- filer/static/filer/js/base.js
- tests/test_models.py
> This PR is a cherry-pick of #1308 plus a simple test to verify that deleting users work. **Thank you @wiltso for providing this fix!**
When deleting a User object, Django's `django.db.models.deletion.Collector` will make a query like this: `File.objects.filter(owner=user).only("id")`.
This then leads to a recursion error due to that the `filer.models.File` object requires that the following fields are present:
- `_file_size`
- `sha1`
- `is_public`
- #1308
- https://github.com/django-cms/django-filer/issues/1290
> fix: File.objects.only("id") query when deleting a user

- .github/workflows/test.yml
- README.rst
- filer/__init__.py
- filer/admin/clipboardadmin.py
- filer/admin/fileadmin.py
- filer/admin/folderadmin.py
- filer/admin/permissionadmin.py
- filer/admin/tools.py
- filer/admin/views.py
- filer/fields/file.py
- filer/fields/folder.py
- filer/fields/multistorage_file.py
- filer/models/abstract.py
- filer/models/clipboardmodels.py
- filer/models/filemodels.py
- filer/models/mixins.py
- filer/models/thumbnailoptionmodels.py
- filer/templatetags/filer_admin_tags.py
- filer/templatetags/filer_tags.py
- filer/thumbnail_processors.py
- filer/utils/compatibility.py
- filer/utils/filer_easy_thumbnails.py
- filer/utils/files.py
- filer/utils/model_label.py
- tests/test_migrations.py
- tox.ini
This PR prepares django-filer for it's 3.0 release. It drops Python 3.7 support and Django 2.2, 3.0, 3.1 support.
Github actions are updates and so is `tox.ini`.
* #...
* #...
> feature: Drop Python 3.7 support, Django 2.2, 3.0 and 3.1 support

- filer/admin/folderadmin.py
- filer/templates/admin/filer/folder/directory_listing.html
When selecting "Search in this folder only" in a non-root folder, the search crashes. 
Also adds a prefetch to optimize folder db hits (only minor improvement).
* #...
* #...
> fix: search in this folder only crashes (500)

- MANIFEST.in
- filer/models/abstract.py
The repo contains an empty mptt stub since app-helper automatically adds it to `INSTALLED_APPS` for test runs. Tests would fail w/o a (potentially empty) mptt package.
The manifest now excludes the stub from the filer package to not interfere with installations that need django-mptt for other reasons.
The mptt stub can be removed from the django-filer repo once app-helper is updated.
* https://github.com/nephila/django-app-helper/pull/224
* #...
> fix: Update manifest to exclude mptt stub in release package

- filer/templates/admin/filer/delete_confirmation.html
- filer/templates/admin/filer/folder/choose_move_destination.html
Testing django-filer 3.0.0rc1 revealed that for "move file" and "delete file" an outdated, unused icon library css is requested. This leads to either a 404 or a 500 (with manifest file storage).
This PR updates the relevant templates.
* #...
* #...
> Fix: Remove unused icon libraries in django-filer 3.0.0rc1

- CHANGELOG.rst
- docs/installation.rst
- filer/apps.py
- filer/management/commands/import_files.py
- filer/models/abstract.py
- filer/settings.py
- setup.py
- tests/requirements/base.txt
This PR adds optional support for upload. To activate, install using `pip install django-filer\[heif\]`.
This installs `pillow-heif`.
* #...
* #...
> Feat: add heif upload support (`*.heic`, e.g., for iOS devices)

- filer/models/foldermodels.py
> Fix: Use `gettext_lazy` for folder model verbose names (#1377)

- filer/templatetags/filer_admin_tags.py
- tests/test_admin.py
Fix crash in filer performing easy-thumbnails thumb-nailing when for some reason the image is not present.
An earlier fix https://github.com/django-cms/django-filer/issues/1379 was done, but it didn't take care of all edge cases, but this one does and gracefully rescues the error and at the same time provides a fallback.
This PR extends #1388 and adds tests.
* #1379
* #1388
> fix: Prevent server errors in image detail view if images do not exist

- filer/admin/folderadmin.py
- tests/test_admin.py
- tests/test_permissions.py
After `django-mptt` removal, copying folders is broken because `insert_at` method is not there anymore.
I've added a regression test that should show the error, and then a fix for it that make the test pass.
* #1392 
> Fix copy folder being broken after django-mptt removal

- filer/templatetags/filer_admin_tags.py
- tests/test_admin.py
In a recent fix, we introduced a regression where we started to access width and height of a file. However, this will only work for images and not for normal files like PDF, Docx etc.
In order to fix this, we need to guard and check if the file is actually an image before trying to access the attributes.
- Github Issue: #1394
> fix: crash in the file detail view

- docs/installation.rst
- filer/admin/clipboardadmin.py
- setup.py
Filer (since 3.0) is only compatible with Django 3.2+. This is reflected in the readme file, but not yet in the docs themselves.
Additional changes:
* Requirement in setup.py
* Type comparison (flake8 error)
* #...
* #...
> docs: Update dependencies in installation.rst

- filer/admin/folderadmin.py
- tests/test_admin.py
This PR intends to hotfix #1415 by reintroducing the `.sort()` function on `file_qs` inside the `filer/admin/folderadmin.py` logic. 
We did not modify any existing tests or added new ones because the function is returning rendered HTML and it is currently unclear how we could test this in an elegant way.
We are also aware that there are better ways to accomplish the same result, e.g. by using Django's `QuerySet.annotate` and `Coalesce` DB functions to add a correct sort target to the queryset, so that `.order_by()` works as intended.
However, we did not want to refactor the existing solution right now but rather hotfix the (currently broken) behaviour.
* See issue #1415 
* https://docs.djangoproject.com/en/4.2/topics/db/aggregation/
* …
> Re-add alphabetical sorting as default (fixes #1415)

- filer/templates/admin/filer/folder/directory_table_list.html
In the CMS admin, when listing the files, we have up to 4 action buttons, with the two firsts "URL" & "Download".
Before this [change](https://github.com/django-cms/django-filer/pull/1360/files#diff-714fc9b6a87e4507da2245171743fa7245805d521413cbcfe23074dc80ebe623R143) : Both were links (one canonical, one to the file in media).
Now both are download links.
IMHO :
* the "download" attribute on the "canonical url" action, is a mistake and should not be added.
* the "download" attribute on the "download" action, is a good and correct improvement to the code.
It became more difficult to display the file in the browser without downloading it. (Now only "right click > open url" allows it.)
So this PR fixes this accordingly.
Also, I noted that the feature name adding the bug was "Styling …
> fix: URL action in data table list template

- filer/static/filer/js/addons/dropzone.init.js
Django 4.1 changed the JavaScript event type being fired when adding a new formset from a jQuery to a vanilla JavaScript event. https://docs.djangoproject.com/en/4.1/ref/contrib/admin/javascript/
This broke the drag-and-drop feature when adding dynamic inlines containing Filer fields in e.g. the Django admin, because the dropzone failed to initialize.
This patch checks for Django 4.1 and initializes the dropzone on newly added inline rows.
This fixes #1400.
> fix: initialize dropzoneSelector inside inline formsets in a Django 4.1 compatible way

- filer/management/commands/filer_check.py
- tests/test_filer_check.py
Basic management command, to insert missing image dimensions.
I've added a test, but can't find instructions on how to setup local tests.
Also, I've only seen conventional commits just now...so...
> feat: Image dimensions update management command

- aldryn_config.py
This change adds compatibility to django 4.2 and the new way storages and handled. 
https://docs.djangoproject.com/en/4.2/releases/4.2/#custom-file-storages
> fix: Added compatibility code in aldryn_config go support setting THUMBNAIL_DEFAULT_STORAGE in django 4.2

- .github/workflows/test.yml
- filer/admin/fileadmin.py
- filer/admin/imageadmin.py
- filer/management/commands/filer_check.py
- filer/templates/admin/filer/tools/detail_info.html
- tests/requirements/base.txt
- tests/test_admin.py
- tests/test_filer_check.py
Fixes the issue mentioned below. As suggested in that thread, I moved the generation of the expand link into the Python code, so that it gets passed to the template via context (which also moves logic from the template to the view layer, which should be a good thing).
While implementing the fix and testing via tox, I found that:
* the recent changes to the `filer_check` command were not compatible with a custom image model either
* while the tox tests have a flag to test with or without a swapped image model, the CI tests running via GitHub actions do not, meaning that there aren't any automated tests with a swapped image model right now
Therefore, I took the liberty to fix the mentioned command and extended the test action matrix with a flag for the image model swap (similar to the tox …
> fix: Compatibility with custom images

- .pre-commit-config.yaml
- CHANGELOG.rst
- filer/__init__.py
- filer/models/foldermodels.py
> Release 2.2.7

- filer/admin/imageadmin.py
Method `clean_subject_location` not implemented correctly.
According to the [Django docs](https://docs.djangoproject.com/en/5.0/ref/forms/validation/#cleaning-a-specific-field-attribute) and to my own experience, a method for cleaning a specific field attribute should not itself call `super().clean()`. This is because this method is invoked later anyway. In the current implementation the method `FileAdminChangeFrom.clean()` is called twice, which in my opinion should not happen.
It also sometimes causes problems if users try to replace an image using the Filer's admin image detail view.
Since no functionality changed, I did not add any extra test.
> method clean_subject_location not implemented correctly

- .github/workflows/publish-to-live-pypi.yml
- .github/workflows/publish-to-test-pypi.yml
> chore: Update release actions

- docs/settings.rst
- filer/admin/fileadmin.py
- filer/admin/folderadmin.py
- filer/fields/file.py
- filer/fields/folder.py
- filer/fields/multistorage_file.py
- filer/models/clipboardmodels.py
- filer/models/filemodels.py
- filer/models/thumbnailoptionmodels.py
- filer/settings.py
- filer/templatetags/filer_tags.py
- tests/helpers.py
- tests/test_admin.py
- tests/test_form_fields.py
- tests/test_migrations.py
- tests/test_models.py
Fixes #1458.
Django 4.2 introduced the new [``STORAGES`` setting](https://docs.djangoproject.com/en/4.2/ref/settings/#storages). The historic ``DEFAULT_FILE_STORAGE`` setting is deprecated and will be removed in Django 5.1. 
This PR makes use of the ``STORAGES`` setting if present, otherwise falls back to ``DEFAULT_FILE_STORAGE`` for compatibility with older Django versions.
https://github.com/fsbraun/django-filer/blob/984a45b71654dc5e4b349b076a726aaa96988d86/filer/settings.py#L62-L65
Also, this PR includes the changes from `pyupgrade` for Python 3.8+
* #1458
* #...
> feat: Accept new `STORAGES` setting, introduced in Django 4.2

- filer/admin/folderadmin.py
- filer/admin/imageadmin.py
- filer/admin/views.py
As requested in #1448 and common practice in the Django admin, this PR makes the admin views return a `TemplateResponse`. 
* #1448
* #...
> feat: Replace `render` with `TemplateResponse` in admin views

- CHANGELOG.rst
- filer/__init__.py
- filer/admin/folderadmin.py
This PR prepares the releaes of django-filer 3.1.4
Changes:
* feat: Accept new `STORAGES` setting, introduced in Django 4.2 by @fsbraun in https://github.com/django-cms/django-filer/pull/1472
* feat: Replace `render` with `TemplateResponse` in admin views by @fsbraun in https://github.com/django-cms/django-filer/pull/1473
* fix: File expand url incorrect and worked not with custom image models by @fsbraun in https://github.com/django-cms/django-filer/pull/1471
* fix: Crash when moving files from a filtered directory listing by @W1ldPo1nter  in https://github.com/django-cms/django-filer/pull/1482
fixes #1479 
* #...
* #...
> chore: Release 3.1.4

- .github/workflows/test.yml
- CHANGELOG.rst
- filer/__init__.py
- filer/cache.py
avoid using type hints that drop support of python 3.8 and 3.9
* https://github.com/django-cms/django-filer/issues/1492
> revert type hint to `typing.List`

- filer/cache.py
Using the AbstractBaseUser for type-hinting the auth user parameter to fix the problem mentioned in issue #1495
* #...
* #...
> fix: Use TypeVar for type-hinting of the user parameter

- filer/static/filer/js/addons/upload-button.js
The attribute exists on the upload button, but it is not read and used.
This PR fix `upload-button.js` to read the value tranform from MiB to bytes and pass the param to FileUploaderBasic object.
By the way, the library used is more than 10 years old of age (2011 ?)  and is not even maintained since 2018 (repo archived)
Also it is strange to have 2 distinct upload mechanisms, one for dropdown and one for upload button.
> fix: uploadButton data-max-filesize attribute is not passed to file-uploader
