filer/__init__.py
filer/apps.py

Creat AppConfig

---

filer/admin/imageadmin.py

Hi, I have a need to edit the author of the image in the admin.

add author to image admin

---

filer/fields/folder.py

Remove is_hidden attribute for FilerFolderField

---

filer/migrations_django/0001_initial.py

Remove migration dependency

---

filer/fields/folder.py

Fix AdminFolderWidget for Django 1.7

---

filer/fields/file.py
filer/fields/folder.py
filer/fields/multistorage_file.py

Fix parameter warnings

---

docs/settings.rst

Fix storages docs

---

filer/static/filer/js/focal_point.js

Try loading image dimensions unless it's allready loaded 250ms after
document.ready.
See: https://github.com/stefanfoulis/django-filer/issues/385

Fix for issue #385

---

.travis.yml
filer/admin/folderadmin.py
filer/admin/patched/admin_utils.py
filer/admin/permissions.py
filer/models/filemodels.py
filer/utils/compatibility.py
setup.py
tox.ini

First batch of Django 1.8 compatibility

---

filer/static/filer/js/focal_point.js

Fix issue #545

---

.travis_setup
filer/fields/file.py
filer/fields/folder.py
filer/fields/image.py
filer/test_utils/test_app/migrations/0001_initial.py
filer/utils/model_label.py
tox.ini

Fix #523 by adding migration dependecy

Fix django18

---

filer/admin/folderadmin.py
filer/views.py

Remove references to request.REQUEST

---

filer/admin/folderadmin.py

Fix #584 (keyerror 'location')

Fix keyerror in folder admin.

---

filer/static/filer/css/admin_style.css
filer/templates/admin/filer/folder/directory_listing.html
filer/templates/admin/filer/folder/directory_table.html

- fixes paste functionality
- it's not possible to add clipboard to changelist form

fixes paste functionality

---

.travis.yml
README.rst
filer/admin/fileadmin.py
filer/admin/folderadmin.py
filer/admin/patched/admin_utils.py
filer/templates/admin/filer/breadcrumbs.html
filer/templates/admin/filer/delete_confirmation.html
filer/templates/admin/filer/folder/change_form.html
filer/templates/admin/filer/folder/directory_listing.html
filer/templates/admin/filer/folder/directory_table.html
filer/templates/admin/filer/tools/clipboard/clipboard.html
filer/templates/admin/filer/tools/upload_button_js.html
filer/utils/compatibility.py
filer/utils/loader.py
setup.py
tox.ini

Almost a complete dupe of https://github.com/stefanfoulis/django-filer/pull/580 but it hasn't moved in a month and is in need of a rebase so I moved everything and resubmitted. Logs are spewing 1.9 warnings so hopefully we can get this released quickly!

Django 1.9 Deprecations

---

README.rst

test for travis

---

CHANGELOG.txt
docs/index.rst
docs/installation.rst
docs/running_tests.rst
setup.py

Adapt doclinks

---

filer/fields/file.py
filer/fields/folder.py
filer/static/filer/js/addons/widget.js
filer/static/filer/js/base.js
filer/templates/admin/filer/folder/directory_listing.html
filer/templates/admin/filer/folder/directory_table.html

Main view scripts fixes, popup fixes, styling fixes.
**Please do not review widget.js**, it's just restored.

Main view scripts fixes, popup fixes, styling fixes

---

filer/admin/clipboardadmin.py

at some point previous regex with ``\d``was broken for subfolders, something escaped the backslash...

Fix admin ajax upload url regex.

---

filer/static/filer/js/addons/dropzone.init.js
filer/static/filer/js/addons/popup_handling.js
filer/static/filer/js/addons/widget.js
filer/templates/admin/filer/widgets/admin_file.html
filer/templates/admin/filer/widgets/lookup.html

This PR fixes the problem when we have multiople upload forms in one plugin in structure mode (carousel slide).
The old styling of **popup_handling.js** and **widget.js** will be fixed later.

Multiple upload forms fix

---

filer/tests/models.py

An attempt to add a workaround for unstable test case. Please, see the test case code/comments for explanation.

Workaround for unstable test cases

---

filer/static/filer/js/addons/dropzone.init.js

Drag and drop on Carousel Plugin fix

Drag and drop on Carousel Plugin fix

---

filer/static/filer/js/addons/table-dropzone.js
filer/templates/admin/filer/folder/directory_table.html

* now the file can be dropped everywhere
* "unfiled files" instead of "root" in popups
* old stuff removed

Updated table drag-n-drop logic

---

CHANGELOG.txt
filer/admin/folderadmin.py

Allow to provide single dimension for resizing images.

Resize image error handling

---

README.rst
docs/running_tests.rst
setup.py
tox.ini

* use stricter Django verison in setup.py
* remove broken support for test runner in setup.py 
* fix tox arguments passing
* update docs

Fix documentation wrt tests and supported versions

---

filer/admin/clipboardadmin.py
filer/settings.py

Handle bad files/filenames AJAX uploads.
This also reorders configured icon sizes and fetches available icons only.

Handle bad file AJAX upload

---

.travis.yml
CHANGELOG.txt
filer/tests/admin.py
filer/tests/models.py
setup.py
tox.ini

Support django 1 9

---

filer/templates/admin/filer/breadcrumbs.html
filer/templates/admin/filer/folder/directory_listing.html
filer/templates/admin/filer/folder/directory_table.html

* Disables the upload button on home page
* Adds upload button to unfiled files

Disables the upload button on home page

---

filer/templates/admin/filer/folder/directory_listing.html
filer/templates/admin/filer/folder/directory_table.html

* fixes of inability to select file after removing smt in popup
* removes unnecessary headers in new folder/delete popups while file selecting

Fixes for popup links

---

filer/templates/admin/filer/breadcrumbs.html

Breadcrumbs fix

---

filer/templates/admin/filer/folder/choose_copy_destination.html
filer/templates/admin/filer/folder/choose_images_resize_options.html
filer/templates/admin/filer/folder/choose_move_destination.html

Submit styling fixes
Some tests are failing here (problems with travis), will fix it together with @mikek soon. Gulp is ok on local machine.

Submit styling fixes

---

filer/static/filer/js/base.js

- search field should be focused on load but small
- on keydown field should resize to bigger field same as on focus

updates search field size on load and on key enter

---

filer/static/filer/js/addons/upload-button.js

So you can find the just uploaded files faster.

Ordering files by last modified after upload

---

filer/admin/folderadmin.py
filer/admin/patched/admin_utils.py
filer/tests/admin.py

fix folder delete view fails

---

filer/templates/admin/filer/delete_selected_files_confirmation.html

- have to add this link as well on filer delete confirmation page

adds back to link on delete confirmation page

---

filer/fields/file.py
filer/static/filer/js/addons/dropzone.init.js
filer/static/filer/js/addons/focal-point.js
filer/static/filer/js/addons/table-dropzone.js
filer/static/filer/js/addons/toggler.js
filer/static/filer/js/addons/upload-button.js
filer/static/filer/js/base.js
filer/templates/admin/filer/base_site.html
filer/templates/admin/filer/file/change_form.html
filer/templates/admin/filer/image/change_form.html

https://github.com/divio/django-filer/issues/736

fixes jQuery conflict issue

---

CHANGELOG.txt
filer/static/filer/js/addons/copy-files.js
filer/templates/admin/filer/folder/choose_copy_destination.html

|BEFORE|AFTER|
|---|---|
|![screen shot 2016-04-06 at 10 29 01](https://cloud.githubusercontent.com/assets/2270884/14310517/8616cabe-fbe2-11e5-9cd1-a87429783e59.png)|![screen shot 2016-04-06 at 10 26 01](https://cloud.githubusercontent.com/assets/2270884/14310521/896a5ac8-fbe2-11e5-9b1a-fbaa760e7e06.png)|

disable submit if only one folder to copy file

---

CHANGELOG.txt
filer/templates/admin/filer/folder/directory_table.html

|BEFORE|AFTER|
|---|---|
|![2016-04-14_1230](https://cloud.githubusercontent.com/assets/2270884/14598015/95050bc2-0550-11e6-829b-fbecd1dc39a0.png)|![screen shot 2016-04-18 at 10 29 50](https://cloud.githubusercontent.com/assets/2270884/14598019/97db5d24-0550-11e6-8958-b0ebb924eb7e.png)|

unsorted uploads empty view

---

filer/models/abstract.py

- fixes focal point if image is smaller thank preview size
- upscales to preview size

upscale preview image to sidebar image width

---

filer/admin/folderadmin.py
filer/models/filemodels.py
filer/models/virtualitems.py
filer/templates/admin/filer/breadcrumbs.html
filer/templates/admin/filer/folder/directory_listing.html
filer/templates/admin/filer/folder/directory_table.html
filer/templates/admin/filer/tools/clipboard/clipboard.html

- renames unfiled files folder name with Unsorted Uploads

renames unfiled files with Unsorted Uploads

---

filer/templates/admin/filer/tools/search_form.html

Different linebreaks between singular and plural confuses gettext

Fix message translation formatting

---

docs/secure_downloads.rst
filer/admin/clipboardadmin.py
filer/admin/folderadmin.py
filer/server/main_server_urls.py
filer/server/thumbnails_server_urls.py
filer/server/urls.py
filer/test_utils/urls.py

Remove all uses of `patterns`

---

.travis.yml
tox.ini

should fix travis frontend failures

install frontend deps manually

---

CHANGELOG.txt
filer/templates/admin/filer/file/change_form.html
filer/templates/admin/filer/image/change_form.html
tox.ini

Fixed markup issue with editing file in admin

---

CHANGELOG.txt
filer/static/filer/js/addons/dropzone.init.js
filer/static/filer/js/addons/table-dropzone.js
filer/static/filer/js/addons/upload-button.js
filer/static/filer/js/base.js

Fixed error message not always showing up properly

---

CHANGELOG.txt
docs/index.rst
docs/management_commands.rst
filer/management/commands/generate_thumbnails.py

Sorry, I f***ed up the rebase in PR #853 here is a new one

Generate thumbnails command

---

CHANGELOG.txt
filer/templates/admin/filer/folder/directory_table.html

Add download button to column action in directory listings

---

docs/development.rst

fix minor typo

---

filer/models/filemodels.py
filer/views.py

Fix #895 
Fixed a couple of issues with the original PR

Merge #895

---

filer/models/filemodels.py

A fix for a regression introduced in #923

Fix new canonical when USE_TZ is False

---

filer/templates/admin/filer/tools/detail_info.html

Display `File.__str__` in the admin change view to match admin list view

---

CHANGELOG.txt
filer/templates/admin/filer/widgets/admin_file.html

Added simple title to file name

---

docs/usage.rst

Example:
```
company.logo  # this is the logo of the company
logo.logo_company  # these are the companies with that logo
```

Related Names work on the opposite direction of FK

---

filer/admin/folderadmin.py

This old comment is extremely misleading (especially when you have custom template)!  :(
See commit https://github.com/divio/django-filer/commit/3718694f73e4560f5ae8bded356987acd85b55a1

Remove wrong comment

---

.travis.yml
docs/extending_filer.rst
filer/admin/__init__.py
filer/admin/clipboardadmin.py
filer/admin/folderadmin.py
filer/admin/imageadmin.py
filer/fields/image.py
filer/management/commands/import_files.py
filer/migrations/0001_initial.py
filer/migrations/0004_auto_20160328_1434.py
filer/migrations/0006_auto_20160623_1627.py
filer/models/abstract.py
filer/models/imagemodels.py
filer/settings.py
filer/test_utils/test_app/migrations/0001_initial.py
filer/tests/admin.py
filer/tests/dump.py
filer/tests/models.py
filer/tests/permissions.py
filer/tests/tools.py
filer/utils/loader.py
test_settings.py
tox.ini

Squashed version of #857 with updated testsuite.

Fix swappable image

---

filer/fields/file.py
filer/settings.py
filer/tests/models.py
filer/utils/loader.py

I think this is the least invasive approach. Also some pre Django 1.8 compat code removed.

Attempt to fix #1002

---

package.json
setup.py
test_requirements/django-1.11.txt

Fixed #990 -- Introduced Django 1.11 support

---

filer/templates/admin/filer/widgets/admin_folder.html

Cherry picked commit for @duartefq 
Fix #1042

Fix: broken reference for delete icon

---

CHANGELOG.txt
filer/models/abstract.py

Merge #1034 after mac os x build fix

Merge #1034

---

CHANGELOG.txt
filer/models/abstract.py

Merge #974

---

filer/admin/folderadmin.py

This is to support better customizability in folderadmin. I was planning to go further with this, but got tangled up with other work. But it can be merged as-is, I think.

use self.get_queryset in folderadmin instead of Folder.objects

---

filer/static/filer/js/addons/dropzone.init.js

Merge #981 with fixes for django 1.8
Fix #986

Merge #981

---

.travis.yml
docs/extending_filer.rst
filer/admin/clipboardadmin.py
filer/migrations/0010_auto_20180414_2058.py
filer/models/abstract.py
filer/test_utils/custom_image/migrations/0003_auto_20180414_2059.py
filer/test_utils/custom_image/models.py
filer/test_utils/extended_app/migrations/0002_auto_20180414_2058.py
filer/tests/models.py
filer/utils/compatibility.py

This provides a bit of cleanup. 
Polymorphic issues with django-polymorphic<2.0 are still there, but other issues with the current implementation have been fixed
Partial fix for #1025

Cleanup swapped Image model

---

setup.py
test_requirements/django-1.11.txt

Allow mptt 0.9

---

filer/admin/imageadmin.py

#1075 
Test coverage provided by #1080
This must be merged before #1080 to allow tests there to run

Convert QueryDict to dict before manipulating in admin

---

docs/settings.rst

howto override single subkeys of FILER_STORAGES

---

setup.py

Needed to raise this dependency for a project and it seems to be working fine - unfortunately, i have no time at hand right now to set up the tox environment properly (it fails at a lot of stuff) so i can't say if it passes tests (sorry for that, wish i had more time).

Raises Unidecode package dependency to v1.0

---

filer/admin/views.py

Added admin site context to make_folder view

---

filer/server/views.py

Added never_cache decorator in server views.

---

CHANGELOG.txt
filer/fields/file.py
filer/fields/folder.py

Fixed #1120 - missing renderer argument for render method

---

CHANGELOG.txt
filer/fields/file.py
filer/fields/folder.py

Fixed #1118 - problem in Django 2.0 and up with getting None instead of object

---

CHANGELOG.txt
filer/__init__.py

* Added support for Django 2.2
* Adapted test matrix
* Adapted test structure and added fixes

Bumped version to 1.5.0

---

CHANGELOG.rst
filer/fields/folder.py
filer/templates/admin/filer/widgets/admin_folder.html

Also makes sure the spacing is correct between button and text:
Fixes #1165

Fixes value error when folder is empty

---

filer/templates/admin/filer/tools/detail_info.html

As explained here: https://www.owasp.org/index.php/Reverse_Tabnabbing

Add rel="noopener noreferrer" for tab nabbing

---

filer/templates/admin/filer/folder/directory_listing.html

Removes minimum visible characters in search field.

Fixes search field overflow #956

---

CHANGELOG.rst
filer/__init__.py

* Removed support for Django <= 1.10
* Removed outdated files
* Code alignments with other addons
* Replace deprecated templatetag ``staticfiles`` against ``static``.
* Added management command ``filer_check`` to check the integrity of the
database against the file system, and vice versa.
* Add jQuery as AdminFileWidget Media dependency
* Add rel="noopener noreferrer" for tab nabbing
* Fixed an issue where a value error is raised when no folder is selected
* Fixed search field overflow

Bumped version to 1.6.0

---

filer/models/foldermodels.py

I made a small change to pull request #1068, because after testing in one of my project, referencing the models directly did not work.

Adopted pull request #1068

---

filer/server/views.py

Patch serve() missing 1 required positional argument: 'filer_file'

---

.github/workflows/docs.yml
.github/workflows/frontend.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.gitignore
setup.cfg

Fixes #1241 and switches from travis to github actions

Switch to github actions

---

filer/admin/folderadmin.py

fixes #1247: see unclassified files when perms are on

---

filer/models/abstract.py
filer/models/clipboardmodels.py
filer/models/filemodels.py
filer/models/foldermodels.py
filer/models/imagemodels.py
filer/models/thumbnailoptionmodels.py

Django provides a [coding style guide](https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#model-style) for models.
This pull request just refactors the code to be compliant with that style guide. There are no functional changes to the code itself. 
This change will therefore not be documented in the Changelog.
https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#model-style

Fix code style

---

setup.py

This updates the meta data to reflect the correct repo URL and adds maintainer information.

fix: Update `setup.py` metadata

---

.pre-commit-config.yaml
CHANGELOG.rst
filer/__init__.py

This updates the changelog and version
* #...
* #...

Bump to version 2.2.5

---

CHANGELOG.rst
filer/__init__.py

Updates version and changelog.
* #...
* #...

ci: Prepare release 3.0.0rc2

---

CHANGELOG.rst
filer/__init__.py

Prepare 3.0.1 release
* #...
* #...

feat: add version in filer and also on changelog

---

CHANGELOG.rst
filer/__init__.py

fix: bump version and add changelog entry

---

CHANGELOG.rst
filer/__init__.py

Add changelog for the new version release.
* #...
* #...

feat: add changelog version

---

CHANGELOG.rst
filer/__init__.py

Bumps version and updates change log
* #...
* #...

ci: Prepare release 3.0.6

---

filer/static/filer/js/addons/dropzone.init.js

This fixes the gulp CI issues I introduced with #1431 
Fixes #1436

fix: address failing gulp ci jobs. 

---

CHANGELOG.rst
filer/__init__.py

The release pull request for version 3.1.2
No code changes.

Bump to version 3.1.2

---

docs/extending_filer.rst

Use latest LTS version links to Django documentation
* #...
* #...

chore(docs): Update extending_filer.rst
